# Generated by Django 4.1.5 on 2023-01-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_more_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('age', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
