# Generated by Django 4.1.5 on 2023-01-31 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_info_dob'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='detail',
        ),
    ]
