# Generated by Django 4.1.5 on 2023-02-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_more_delete_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('age', models.CharField(max_length=12)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='more',
        ),
    ]
