# Generated by Django 4.1.5 on 2023-02-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_feedback_delete_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('gender', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('age', models.CharField(max_length=12)),
                ('place', models.CharField(max_length=122)),
                ('occupation', models.CharField(max_length=122)),
            ],
        ),
    ]
