# Generated by Django 4.1.5 on 2023-02-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='place',
            new_name='address',
        ),
    ]
