# Generated by Django 4.1.5 on 2023-02-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_place_userinfo_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('item', models.CharField(max_length=122)),
                ('item_no', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
